apps/public/tailwind.config.ts
package.json

chore: add primary color from env

---

apps/public/components/ui/carousel.tsx
apps/public/package.json
pnpm-lock.yaml

feat: shadcn carousel component

---

apps/public/_data/projects.ts
apps/public/_types/index.ts
apps/public/_types/projects.ts

feat: add project data and types for eco-friendly initiatives

---

apps/public/app/login/page.tsx

fix: correct redirect path in login page

---

apps/public/components/HeroSection.tsx

feat: update HeroSection with new layout and background image

---

apps/public/components/DetailsSection.tsx

feat: update DetailsSection layout and content for improved presentation

---

publish-cli.sh

feat: add publish-cli script for managing app deployments and updates

---

publish-cli.sh

feat: enhance publish script

---

apps/public/components/IconWrapper.tsx

feat: add IconWrapper component for consistent icon styling

---

apps/public/_data/index.tsx
apps/public/_data/missions.tsx
apps/public/_types/missions.ts
apps/public/app/page.tsx
apps/public/components/MissionSection.tsx

feat: MissionsSection

---

apps/web/package.json
apps/web/src/utils/navbar/core-navbar-items.json
apps/web/src/utils/navbar/groups.tsx
packages/ui/package.json
pnpm-lock.yaml

chore: update react versions

---

apps/public/app/(dashboard)/layout.tsx
apps/public/app/(dashboard)/projects/new/basics/page.tsx
apps/public/app/(dashboard)/projects/new/layout.tsx
apps/public/app/(landing)/layout.tsx
apps/public/app/layout.tsx
apps/public/components/Datepicker.tsx

refactor: improve layout

---

publish-cli.sh

refactor: add warning for missing .env file in publish-cli.sh

---

publish-cli.sh

refactor: improve app name formatting and simplify port prompt publish.cli

---

publish-cli.sh

refactor: correct project name retrieval and change warning to error

---

publish-cli.sh

refactor: simplify app name generation and update start_app function

---

publish-cli.sh

refactor: improve argument handling in publish-cli.sh

---

.github/workflows/lint-main.yml
.github/workflows/lint-pull-requests.yml
.github/workflows/publish-dev.yml

refactor: update workflow names and streamline publish-dev job

---

.github/workflows/publish-dev.yml

refactor: update path in publish-dev workflow for deployment script

---

publish-cli.sh

refactor: optimize pm2 process check in start_app function 

---

apps/public/app/(auth)/layout.tsx

fix: adjust carousel initial state and layout grid configuration

---

CLEANCODE.md
apps/public/app/(dashboard)/profile/new/business/page.tsx
apps/public/app/(dashboard)/profile/new/personal/page.tsx
apps/public/app/(dashboard)/profile/page.tsx
apps/public/auth.ts
apps/public/package.json
apps/public/utils/client.ts
pnpm-lock.yaml

docs: add CLEANCODE.md

---

apps/public/next.config.mjs

fix: update transpilePackages to use @ayasofyazilim/upwithcrowd-saas

---

apps/public/actions/api-utils-client.ts
apps/public/actions/upwithcrowd/project/action.ts
apps/public/actions/upwithcrowd/public-project/actions.ts

feat: Implement API response handlers for CRUD operations and public

---

apps/public/app/(dashboard)/profile/payments/client.tsx
apps/public/app/(dashboard)/profile/payments/page.tsx
apps/public/app/(landing)/projects/[id]/client.tsx

feat: A draft design was created for the Payment page, divided into server-side and client-side.

---

apps/public/app/(auth)/login/loading.tsx
apps/public/app/(landing)/projects/page.tsx
apps/public/auth.ts
apps/public/middleware.ts
apps/web/src/app/[lang]/(main)/(core)/management/identity/organization/action.ts
apps/web/src/app/[lang]/(main)/(core)/management/identity/organization/form.tsx
apps/web/src/app/[lang]/(main)/(core)/management/identity/organization/page.tsx
apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/_components/form.tsx
apps/web/src/app/[lang]/(main)/(core)/management/identity/users/new/_components/form.tsx
apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/_components/applications-table-data.tsx
apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/_components/table.tsx
apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/page.tsx
apps/web/src/utils.ts

refactor: remove unnecessary console log and clean up project

---

apps/public/.env.example
apps/public/auth.ts

feat: update authentication URLs to use NEXT_AUTH_URL environment var

---

apps/public/actions/upwithcrowd/project/post-action.ts
apps/public/app/(dashboard)/projects/new/_components/faq-card.tsx
apps/public/app/(dashboard)/projects/new/_components/form.tsx
apps/public/app/(dashboard)/projects/new/_components/user-card.tsx
apps/public/app/(dashboard)/projects/new/_components/vanity-url.tsx
apps/public/app/(dashboard)/projects/new/layout.tsx
apps/public/app/(dashboard)/projects/new/people/page.tsx
apps/public/app/(dashboard)/projects/new/story/page.tsx
apps/public/tsconfig.json

feat: add FAQ builder component and integrate into project story page

---

apps/public/actions/upwithcrowd/project/post-action.ts
apps/public/app/(dashboard)/projects/new/basics/page.tsx
apps/public/app/(landing)/projects/page.tsx

feat: add project creation functionality and enhance project listing

---

apps/public/app/(landing)/projects/[id]/client.tsx

feat: enhance project details page with blog post and table of contents

---

apps/public/actions/upwithcrowd/project/action.ts
apps/public/app/(dashboard)/profile/_components/listed-project-card.tsx
apps/public/app/(dashboard)/profile/projects/page.tsx
apps/public/app/(dashboard)/projects/new/basics/page.tsx

feat(projects): implement my projects API and enhance project listing UI

---

apps/public/actions/api-utils-client.ts
apps/public/actions/upwithcrowd/my-member/actions.ts
apps/public/actions/upwithcrowd/project/action.ts
apps/public/actions/upwithcrowd/project/post-action.ts
apps/public/actions/upwithcrowd/public-project/actions.ts
apps/public/app/(auth)/login/action.ts
apps/public/app/(auth)/signup/action.ts
apps/public/app/(dashboard)/projects/new/story/page.tsx
apps/public/app/api/auth/[...nextauth]/route.ts
apps/public/app/layout.tsx
apps/public/middleware.ts
apps/public/next.config.mjs
apps/public/package.json
apps/public/tsconfig.json
apps/public/utils/client.ts
pnpm-lock.yaml

refactor: update import paths to use @repo/utils for consistency

---

apps/web/.env.example
apps/web/src/actions/core/AccountService/actions.ts
apps/web/src/app/[lang]/(main)/layout.tsx
apps/web/src/app/api/auth/[...nextauth]/route.ts
apps/web/src/app/layout.tsx
apps/web/src/lib.ts
apps/web/src/middleware.ts
packages/utils/auth/auth-actions.ts
packages/utils/auth/auth-types.ts
packages/utils/auth/auth.ts
packages/utils/auth/index.tsx
packages/utils/package.json
turbo.json

chore: core

---

publish-cli.sh

feat:update cli

---

apps/public/app/providers/member.tsx
apps/public/utils/types.d.ts

feat(MemberProvider):add provider to managing member state

---

apps/public/actions/upwithcrowd/member/actions.ts

feat: make data parameter optional in getApiMemberApi function

---

apps/public/app/(auth)/login/page.tsx
apps/public/app/layout.tsx
apps/public/app/providers/member.tsx
apps/public/app/providers/providers.tsx
apps/public/components/Header.tsx
apps/public/components/member-switcher.tsx

feat: implement member switching functionality and session management

---

apps/web/src/app/layout.tsx
packages/ui/src/theme/main-admin-layout/header-section.tsx

chore:update project's core

---

apps/public/package.json
pnpm-lock.yaml

chore(deps): update packages

---

apps/public/actions/upwithcrowd/project/action.ts
apps/public/app/(dashboard)/profile/_components/listed-project-card.tsx
apps/public/app/(dashboard)/profile/projects/page.tsx

feat(api): add getProjectApi function and update project data handling

---

apps/public/app/providers/member.tsx
apps/public/components/member-switcher.tsx

feat(member-switcher): enhance member handling and add mobile support

---

apps/public/actions/upwithcrowd/account/post-action.ts
apps/public/actions/upwithcrowd/my-profile/put-action.ts
apps/public/actions/upwithcrowd/project/action.ts
apps/public/actions/upwithcrowd/user-members/post-action.ts
apps/public/actions/upwithcrowd/user/put-action.ts
apps/public/app/(auth)/layout.tsx
apps/public/app/(auth)/login/page.tsx
apps/public/app/(dashboard)/profile/new/personal/client.tsx
apps/public/app/(dashboard)/profile/new/personal/page.tsx
apps/public/app/(dashboard)/profile/page.tsx
apps/public/app/(dashboard)/projects/[id]/basics/client.tsx
apps/public/components/member-switcher.tsx
apps/public/package.json
apps/public/utils/client.ts
apps/public/utils/types.d.ts
pnpm-lock.yaml

chore(package): update recharts to version 2.15.1

---

apps/public/actions/upwithcrowd/member/put-action.ts
apps/public/actions/upwithcrowd/user-members/action.ts
apps/public/app/(dashboard)/profile/new/business/client.tsx
apps/public/app/(dashboard)/profile/new/personal/client.tsx
apps/public/app/(dashboard)/profile/page.tsx
apps/public/app/(landing)/projects/[id]/client.tsx
apps/public/app/layout.tsx
apps/public/app/providers/member.tsx
apps/public/components/member-switcher.tsx
apps/public/utils/client.ts
apps/public/utils/types.d.ts
pnpm-lock.yaml

chore(deps): update dependencies to latest versions

---

apps/public/app/(dashboard)/profile/new/business/client.tsx
apps/public/tsconfig.json

Update from es5 to es6

---

apps/public/actions/upwithcrowd/member/put-action.ts
apps/public/app/(dashboard)/profile/_components/empty-payments-state.tsx
apps/public/app/(dashboard)/profile/_components/indiviual-form.tsx
apps/public/app/(dashboard)/profile/_components/organization-form.tsx
apps/public/app/(dashboard)/profile/page.tsx
apps/public/app/(dashboard)/profile/payments/page.tsx
apps/public/app/(dashboard)/profile/settings/client.tsx
apps/public/app/(dashboard)/profile/settings/page.tsx
apps/public/app/(landing)/projects/[id]/client.tsx
apps/public/app/(landing)/projects/[id]/page.tsx

feat(project): add editable state to ProjectDetails component

---

apps/public/app/(dashboard)/profile/payments/page.tsx
apps/public/components/member-switcher.tsx

feat(payments): update project API import to use getPublicProjectsApi

---

apps/public/app/(dashboard)/layout.tsx

chore:layout

---

apps/public/actions/upwithcrowd/member/actions.ts
apps/public/actions/upwithcrowd/project/action.ts
apps/public/actions/upwithcrowd/project/post-action.ts
apps/public/actions/upwithcrowd/roles/action.ts
apps/public/app/(dashboard)/projects/[id]/about/client.tsx
apps/public/app/(dashboard)/projects/[id]/about/page.tsx
apps/public/app/(dashboard)/projects/new/basics/page.tsx
apps/public/package.json
pnpm-lock.yaml

create Hakkımızda page and added project member section

---

apps/public/app/(landing)/projects/_components/search-bar.tsx
apps/public/app/(landing)/projects/_components/sort-selector.tsx
apps/public/app/(landing)/projects/page.tsx

fix sort problem

---

apps/public/app/(landing)/projects/[id]/page.tsx

fix:project detail problem

---

apps/web/src/app/[lang]/(main)/layout.tsx
apps/web/src/providers/novu.tsx
apps/web/src/providers/providers.tsx
apps/web/src/utils/navbar/notification.tsx
packages/utils/helper-functions.ts
packages/utils/package.json

merge core into upwc

---

.github/workflows/publish.yml

chore(workflows): update publish workflow to include app input options

---

apps/public/app/api/route.tsx
apps/public/app/providers/locale.tsx
apps/public/package.json
pnpm-lock.yaml

chore(lang): preperation for locale in public upwithcrowd

---

apps/public/components/call-to-action.tsx
apps/public/components/details-section.tsx
apps/public/components/footer.tsx
apps/public/components/hero-section.tsx
apps/public/components/mission-section.tsx
apps/public/components/testimoni.tsx

refactor: improve layout and styling of various components for better responsiveness and visual consistency

---

apps/public/actions/upwithcrowd/project/action.ts
apps/public/app/[lang]/(dashboard)/profile/projects/page.tsx

refactor(project): use new api actions and handling

---

apps/public/actions/upwithcrowd/member/actions.ts
apps/web/.eslintrc.js
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/[memberType]/[type]/page.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/_components/member-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/_components/table.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/[fundCollectionType]/[projectStateType]/page.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/_components/project-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/_components/table.tsx
packages/ui/src/theme/alternative-admin-layout/index.tsx
packages/ui/src/theme/auth/login/index.tsx
packages/ui/src/theme/auth/new-password/index.tsx
packages/ui/src/theme/auth/register/index.tsx
packages/ui/src/theme/auth/reset-password/index.tsx

feat(projects&community): add pages

---

apps/public/app/[lang]/(dashboard)/profile/_components/listed-project-card.tsx
apps/public/app/[lang]/(landing)/projects/page.tsx
apps/public/package.json
pnpm-lock.yaml

fix: update project card components to handle project URLs 

---

apps/public/actions/upwithcrowd/project/action.ts
apps/public/actions/upwithcrowd/tasks/action.ts
apps/public/actions/upwithcrowd/tasks/post-action.ts
apps/public/app/[lang]/(dashboard)/profile/layout.tsx
apps/public/app/[lang]/(dashboard)/profile/support/_components/table.tsx
apps/public/app/[lang]/(dashboard)/profile/support/client.tsx
apps/public/app/[lang]/(dashboard)/profile/support/page.tsx
apps/public/app/[lang]/(dashboard)/profile/support/support-form/page.tsx
apps/public/app/[lang]/(dashboard)/projects/[id]/basics/page.tsx
apps/public/app/[lang]/(landing)/projects/[id]/page.tsx
apps/public/components/member-switcher.tsx

feat: add support request feature with task management and UI components

---

apps/public/app/[lang]/(dashboard)/profile/page.tsx
apps/public/app/providers/member.tsx
apps/public/components/member-switcher.tsx

fix: clear sessionStorage on logouts

---

apps/public/actions/core/AccountService/actions.ts
apps/public/app/[lang]/layout.tsx

chore: logout when token is expired

---

apps/public/actions/upwithcrowd/task-comment/action.ts
apps/public/actions/upwithcrowd/task-comment/post-action.ts
apps/web/src/app/[lang]/(main)/(upwithcrowd)/support-center/[tasksType]/[roleType]/client.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/support-center/[tasksType]/[roleType]/page.tsx

feat(api): add task and task comment API actions

---

apps/public/app/providers/providers.tsx

feat: novu provider to public

---

apps/web/src/app/[lang]/(main)/(upwithcrowd)/support-center/[tasksType]/[roleType]/client.tsx
packages/ui/src/theme/alternative-admin-layout/components/header-section.tsx

feat(web): add empty state message for support requests

---

apps/public/app/[lang]/(dashboard)/layout.tsx
apps/public/app/[lang]/(landing)/layout.tsx
apps/public/components/header.tsx
packages/ui/src/components/notification.tsx

feat: integrate notification system into layout and header components

---

apps/web/src/app/globals.css
packages/ui/src/theme/alternative-admin-layout/components/app-sidebar.tsx
packages/ui/src/theme/alternative-admin-layout/index.tsx

feat: enhance AppSidebar with user profile and notification integration

---

apps/web/src/app/[lang]/(main)/(upwithcrowd)/files/_components/file-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/files/_components/table.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/files/page.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/files/type.ts
packages/ui/src/theme/alternative-admin-layout/index.tsx

chore(web): add example files page

---

apps/public/app/[lang]/(dashboard)/projects/new/basics/client.tsx
apps/public/app/[lang]/(landing)/projects/[id]/client.tsx

fix: update redirect path after project save to 'about' page

---

apps/public/actions/upwithcrowd/category-project/action.ts
apps/public/actions/upwithcrowd/images/action.ts
apps/public/actions/upwithcrowd/public-project/actions.ts
apps/public/app/[lang]/(dashboard)/projects/[id]/basics/page.tsx
apps/public/app/[lang]/(dashboard)/projects/[id]/finish-project/page.tsx
apps/public/app/[lang]/(dashboard)/projects/new/basics/page.tsx
apps/public/app/[lang]/(landing)/projects/[id]/page.tsx

refactor(api): update get functions with throw

---

apps/public/app/[lang]/(landing)/layout.tsx

fix: update layout section to prevent overflow and improve display

---

packages/ui/src/theme/alternative-admin-layout/components/header-section.tsx
packages/ui/src/theme/alternative-admin-layout/index.tsx

fix(web): layout is missing on mobile

---

apps/public/actions/upwithcrowd/member/actions.ts
apps/public/app/[lang]/layout.tsx

…e API requests in layout## Description
…e API requests in layout

refactor(layout): fix member list assignment and ensure active member retrieval in RootLayout component

---

apps/public/actions/upwithcrowd/project/action.ts
apps/public/app/[lang]/(landing)/projects/[id]/page.tsx
apps/public/language/resources.ts

feat: add API for project update permissions and integrate into proje

---

apps/public/app/[lang]/(landing)/projects/[id]/client.tsx
apps/public/app/[lang]/(landing)/projects/[id]/page.tsx

fix(public/project): project detail page gives unauthorized when you are not logged in

---

apps/public/package.json
apps/web/package.json
package.json
pnpm-lock.yaml

>    "saas": "pnpm i @ayasofyazilim/upwithcrowd-saas@latest --filter ./apps/*"
i added this script to root package.json so we can update saas by simply run  ```pnpm saas```

chore:update saas (READ DESCRIPTION)

---

apps/public/actions/upwithcrowd/project/action.ts
apps/public/app/[lang]/(dashboard)/profile/support/support-form/page.tsx
apps/public/app/[lang]/(landing)/projects/[id]/page.tsx
apps/public/language/resources.ts

feat(support-form): update project selection to use AsyncSelect

---

apps/web/src/app/[lang]/(main)/layout.tsx
packages/ui/src/theme/alternative-admin-layout/components/app-sidebar.tsx
packages/ui/src/theme/alternative-admin-layout/components/navbar.tsx
packages/ui/src/theme/alternative-admin-layout/index.tsx

feat(alternative-layout/navbar): add badge support

---

apps/public/app/[lang]/(landing)/projects/[id]/_components/documents-card.tsx
apps/public/app/[lang]/(landing)/projects/[id]/client.tsx
apps/public/next.config.mjs

feat(projectsDetail): add DocumentsCard component for file display and management

---

packages/actions/upwithcrowd/lib.ts
packages/actions/upwithcrowd/mime-type/actions.ts

feat: add Upwithcrowd client and API actions for mime type handling

---

apps/public/package.json
apps/web/package.json
packages/actions/package.json
pnpm-lock.yaml

chore: updated saas

---

apps/web/src/app/[lang]/(main)/(upwithcrowd)/management/file/file-type-groups/page.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/management/file/providers/_components/providers-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/management/file/providers/_components/table.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/management/file/providers/page.tsx
packages/actions/upwithcrowd/providers/delete-actions.ts
packages/actions/upwithcrowd/providers/post-actions.ts
packages/actions/upwithcrowd/providers/put-actions.ts
packages/ui/src/theme/alternative-admin-layout/index.tsx

feat(providers): add CRUD operations for providers with API integration

---

apps/public/app/[lang]/(auth)/mail-verification/page.tsx
packages/actions/core/AccountService/post-actions.ts

feat(mail-verification): implement mail verification page and API integration

---

packages/actions/upwithcrowd/file-type-group/actions.ts
packages/ui/src/upwithcrowd/file-upload/file-upload-base.tsx
packages/ui/src/upwithcrowd/file-upload/index.tsx

Usage
```tsx
async function getApiRequests() {
try {
const session = await auth();
const requiredRequests = await Promise.all([getFileTypeGroupTestApi({namespace: "Project"}, session)]);
const optionalRequests = await Promise.allSettled([]);
return {requiredRequests, optionalRequests};
} catch (error) {
if (!isRedirectError(error)) {
return structuredError(error);
}
throw error;
}
}
export default async function Page({
params,
}: {
params: {
lang: string;
};
}) {
const {lang} = params;
const {languageData} = await getResourceData(lang);
const apiRequests = await getApiRequests();
if ("message" in apiRequests) {
return <ErrorComponent languageData={languageData} message={apiRequests.message} />;
}
const [fileTypeGroupTestResponse] = apiRequests.requiredRequests;
return (
<FileUpload …
```

feat(file-upload): implement file upload component with validation and API integration

---

apps/public/components/header.tsx

fix: restore Notification component usage in Header

---

apps/public/app/[lang]/(landing)/layout.tsx

feat: enhance layout component to include notification handling based on user session

---

apps/public/app/[lang]/(dashboard)/projects/[id]/about/client.tsx
apps/public/app/[lang]/(landing)/projects/[id]/client.tsx
apps/public/app/[lang]/(landing)/projects/[id]/page.tsx
apps/public/package.json
apps/web/package.json
packages/actions/package.json
packages/actions/upwithcrowd/public-file/action.ts
pnpm-lock.yaml

chore: update upwithcrowd-saas dependency to version 0.0.48

fix: handle null investor response in project details

---

apps/public/app/api/file/route.ts
apps/web/src/app/api/file/route.ts
packages/ui/src/upwithcrowd/file-upload/_components/container.tsx
packages/ui/src/upwithcrowd/file-upload/_components/file-upload-base.tsx
packages/ui/src/upwithcrowd/file-upload/_components/success-list.tsx

feat: implement file upload API and enhance file upload component

---

apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/_components/member-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/[projectId]/page.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/_components/file-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/_components/table.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/page.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/_components/file-table-data.tsx
apps/web/src/language-data/resources.ts
packages/actions/upwithcrowd/file/actions.ts

closes [#1332](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1332)

feat(admin): add member detail(file) & add member file validation & add project file validation 

---

packages/ui/src/upwithcrowd/file-upload/_components/file-upload-base.tsx
packages/ui/src/upwithcrowd/file-upload/index.tsx

feat: enhance FileUpload component with MultiSelect for rule selection

---

apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/_components/member-table-data.tsx
packages/actions/upwithcrowd/member/put-action.ts

refactor(admin/member): change validate api call with correct endpoint

---

apps/public/package.json
apps/web/package.json
apps/web/src/app/[lang]/(main)/(upwithcrowd)/management/file/file-type-mime-types/_components/file-type-mime-type-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/notification-center/_components/send-notification-form.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/notification-center/client.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/notification-center/page.tsx
packages/actions/package.json
packages/ui/package.json
packages/ui/src/theme/alternative-admin-layout/index.tsx
packages/ui/src/upwithcrowd/novu/send-notification-form/index.tsx
pnpm-lock.yaml

feat(notification-center): implement send notification form & saas update

---

packages/ui/src/upwithcrowd/file-upload/_components/container.tsx
packages/ui/src/upwithcrowd/file-upload/_components/file-upload-base.tsx
packages/ui/src/upwithcrowd/file-upload/index.tsx

…back and improved type handling

feat(file-upload): enhance file upload components with onSuccess callback and improved type handling

---

apps/public/app/[lang]/(dashboard)/profile/_components/listed-project-card.tsx
apps/public/app/[lang]/(dashboard)/profile/documents/document-upload/page.tsx
apps/public/app/[lang]/(dashboard)/profile/new/business/page.tsx
apps/public/app/[lang]/(dashboard)/projects/[id]/documents/client.tsx
apps/public/app/[lang]/(dashboard)/projects/[id]/documents/page.tsx
apps/public/app/[lang]/(dashboard)/projects/[id]/images/page.tsx
apps/public/app/[lang]/(dashboard)/projects/[id]/information-form/page.tsx
apps/public/app/[lang]/(landing)/projects/page.tsx
apps/public/package.json
apps/web/package.json
packages/actions/package.json
packages/actions/upwithcrowd/file-type-group/actions.ts
pnpm-lock.yaml

chore:update saas

---

apps/public/app/[lang]/layout.tsx

chore:revert deletion myProfile api

---

apps/public/app/[lang]/(dashboard)/profile/_components/listed-project-card.tsx
apps/public/app/[lang]/(dashboard)/projects/[id]/basics/client.tsx
apps/public/app/[lang]/(dashboard)/projects/[id]/basics/page.tsx
apps/public/app/[lang]/(dashboard)/projects/new/basics/client.tsx
apps/public/app/[lang]/(landing)/projects/[id]/_components/auth-card.tsx
apps/public/app/[lang]/(landing)/projects/[id]/client.tsx
apps/public/app/providers/member.tsx
packages/actions/upwithcrowd/project/action.ts
pnpm-lock.yaml

feat(profile): calculate and display accurate funded percentage in project card

---

apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/client.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/layout.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/page.tsx

…data preparation## Description

feat(project-detail): implement client page for project details with ….

---

apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/about/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/funding/client.tsx

feat(dashboard/projects/funding): enhance funding form with improved validation and user feedback

---

apps/public/package.json
apps/web/package.json
packages/actions/package.json
pnpm-lock.yaml

chore(dependencies): update @ayasofyazilim/upwithcrowd-saas to version 0.0.51

---

apps/public/app/[lang]/(dashboard)/dashboard/(others)/notice/[id]/page.tsx

feat(notifications): replace custom notification form with SendNotificationForm component

---

apps/public/app/[lang]/(dashboard)/dashboard/(others)/member/_components/business-account-modal.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(others)/member/settings/client.tsx

feat(business-account-modal): enhance modal with user validation button and routing

---

apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/about/client.tsx
apps/public/app/[lang]/(landing)/projects/[id]/client.tsx
apps/public/app/[lang]/(landing)/projects/[id]/page.tsx
apps/public/package.json
apps/web/package.json
packages/actions/package.json
packages/ui/src/upwithcrowd/project-components/auth-card.tsx
packages/ui/src/upwithcrowd/project-components/funding-card.tsx
packages/ui/src/upwithcrowd/project-components/project-team.tsx
pnpm-lock.yaml

fix: saas update & update related changes

---

apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/_components/table.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/investments/page.tsx

feat(ProjectInvestors): manage paging

---

apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/_components/table.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/investors/_components/investors-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/investors/_components/table.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/investors/page.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/layout.tsx

closes [#1344](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1344)

feat(ProjectDetails): list investors of project and transfer to mkk action

---

apps/public/app/[lang]/(dashboard)/dashboard/(others)/page.tsx

refactor(dashboard): comment out organization link rendering logic

---

apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/[[...slug]]/page.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/_components/member-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/_components/table.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/[memberId]/files/_components/file-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/[memberId]/files/_components/table.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/[memberId]/files/page.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/[memberId]/investments/_components/investment-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/[memberId]/investments/_components/table.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/[memberId]/investments/page.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/[memberId]/layout.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/[memberId]/page.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/_components/project-table-data.tsx

…
closes #[#1349](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/1349)

feat(CommunityDetail): refactor member and investment tables, add file handling components

---

apps/public/app/[lang]/(dashboard)/dashboard/(others)/_components/empty-projects-state.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(others)/member/new/personal/client.tsx
packages/ui/src/upwithcrowd/file-upload/_components/container.tsx
packages/ui/src/upwithcrowd/file-upload/_components/file-upload-base.tsx
packages/ui/src/upwithcrowd/file-upload/_components/form.tsx

feat(dashboard): update project creation link and enhance session handling in personal account

---

apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/documents/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/images/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/information-form/client.tsx

chore: refactor file upload handling in projectEdit components

---

apps/public/app/[lang]/layout.tsx
packages/ui/src/components/error-component.tsx

feat: add clearSession prop to ErrorComponent for session management

---

apps/public/components/project-slider.tsx

fix(project-slider): adjust margin for improved layout

---

apps/public/components/header.tsx
apps/public/components/project-slider.tsx

fix(landing/home): fixed project image invisibility and updated header responsive

---

apps/public/app/[lang]/(landing)/projects/[id]/@modal/(.)investors/modal.tsx
apps/public/app/[lang]/(landing)/projects/[id]/@modal/(.)investors/page.tsx
apps/public/app/[lang]/(landing)/projects/[id]/@modal/default.tsx
apps/public/app/[lang]/(landing)/projects/[id]/investors/page.tsx
apps/public/app/[lang]/(landing)/projects/[id]/layout.tsx
apps/public/app/[lang]/(landing)/projects/[id]/page.tsx
packages/ui/src/upwithcrowd/project-components/investors-card.tsx
packages/ui/src/upwithcrowd/project-components/project-template.tsx

feat(projects): add investor modal & pagination

---

apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/about/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/about/page.tsx

fix(project/about): fixed select role for add member process

---

apps/public/package.json
apps/web/package.json
packages/actions/package.json
pnpm-lock.yaml

fix(dependencies): update @ayasofyazilim/upwithcrowd-saas to version 

---

packages/ui/src/upwithcrowd/file-upload/_components/container.tsx
packages/ui/src/upwithcrowd/file-upload/_components/file-upload-base.tsx
packages/ui/src/upwithcrowd/file-upload/index.tsx

feat(file-upload): add disabled prop to file upload components

---

apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/about/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/about/page.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/basics/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/basics/page.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/documents/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/documents/page.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/funding/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/funding/page.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/images/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/images/page.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/information-form/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/information-form/page.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/investments/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/investments/page.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/layout.tsx

feat(dashboard): add isDisable prop to control button states project dashboard

---

apps/public/package.json
apps/web/package.json
packages/actions/package.json
pnpm-lock.yaml

fix: update @ayasofyazilim/upwithcrowd-saas dependency to version 0.0.56

---

apps/public/app/[lang]/(dashboard)/dashboard/(others)/member/_components/member-file-table-data.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/about/page.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/documents/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/images/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/information-form/client.tsx
apps/public/app/api/file/[fileId]/download/route.ts

feat(Public): implement file download functionality

---

apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/basics/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/funding/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/new/basics/client.tsx

fix: update TiptapEditor props and remove unused funding fields

---

apps/public/app/[lang]/(dashboard)/dashboard/(others)/member/_components/indiviual-form.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(others)/member/_components/organization-form.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(others)/member/settings/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(others)/member/settings/page.tsx

feat: enhance NewPersonalAccount component with memberId prop 

---

packages/ui/src/upwithcrowd/project-components/project-template.tsx

feat: add file download functionality to patent and legal file sections

---

apps/web/src/app/[lang]/(main)/(upwithcrowd)/management/file/file-relation-entities/_components/file-relation-entity-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/management/file/file-type-mime-types/_components/file-type-mime-type-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/management/file/file-type-mime-types/_components/table.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/management/file/mime-types/_components/mime-type-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/client.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/page.tsx

refactor: update type imports and enhance project detail components with statistics

---

packages/ui/src/upwithcrowd/project-components/project-summary.tsx
packages/ui/src/upwithcrowd/project-components/project-template.tsx

feat: enhance project summary layout with category and sector badges

---

apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/_components/member-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/_components/table.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/[memberId]/page.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/_components/member-actions.tsx

feat: implement member validation actions and refactor member detail page

---

apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/new/basics/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/new/layout.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/new/page.tsx

fix: remove trailing slash from project basics links

---

apps/public/app/[lang]/(dashboard)/dashboard/(others)/projects/_components/filter-selector.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(others)/projects/page.tsx
apps/public/app/[lang]/(landing)/projects/_components/filter-selector.tsx
apps/public/app/[lang]/(landing)/projects/page.tsx
pnpm-lock.yaml

feat: add sector filtering to project listings and enhance API requests for sectors

---

apps/public/app/[lang]/(dashboard)/dashboard/(others)/member/new/business/client.tsx
apps/public/app/[lang]/(dashboard)/dashboard/(others)/member/new/business/page.tsx

feat: enhance NewBusinessAccountForm to navigate to settings on successful member update

---

apps/public/app/[lang]/(dashboard)/layout.tsx
apps/public/app/[lang]/(landing)/layout.tsx
apps/public/components/header.tsx
apps/public/components/member-switcher.tsx
packages/ui/src/upwithcrowd/file-upload/_components/container.tsx
packages/ui/src/upwithcrowd/file-upload/_components/file-upload-base.tsx
packages/ui/src/upwithcrowd/file-upload/index.tsx

feat: simplify Header component by removing appName prop and adjust layout styles

---

packages/ui/src/upwithcrowd/project-components/funding-card.tsx
packages/ui/src/upwithcrowd/project-components/project-template.tsx

fix: update funding card to display qualified investor count as a string & refactor: reorganize imports in project template for better readability

---

apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/[memberId]/files/_components/file-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/detail/[memberId]/investments/_components/investment-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/files/_components/file-table-data.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/investors/_components/investors-table-data.tsx

refactor: update language keys in file and investment table components for improved clarity

---

apps/web/src/app/[lang]/(main)/(upwithcrowd)/notification-center/client.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/_components/project-actions.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/client.tsx
apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/layout.tsx
apps/web/src/language-data/resources.ts

refactor: adjust grid layouts and component placements in notification center and project details

---

apps/public/app/[lang]/(dashboard)/dashboard/(others)/member/new/personal/client.tsx
apps/public/app/providers/member.tsx

refactor: update handlePostResponse to use base link for dashboard na

---

apps/public/app/[lang]/(dashboard)/dashboard/(projects)/projects/[id]/funding/client.tsx

refactor: update funding schema to use coercion for rates and increase privilege character limit

---

apps/web/src/app/[lang]/(main)/(upwithcrowd)/projects/detail/[projectId]/images/client.tsx
apps/web/src/language-data/resources.ts

feat: add file type determination for images and videos in client component

---

apps/web/src/app/[lang]/(main)/(upwithcrowd)/community/_components/member-table-data.tsx

feat: add corporate phone and email fields to member table data
